version: '3.3'
services:

  bitcoind:
    image: ruimarinho/bitcoin-core
    container_name: bitcoind
    volumes:
      - ${PWD}/data:/root/.bitcoin:ro
      - ${PWD}/data:/home/bitcoin/.bitcoin
    command:
      bitcoind
      -server
      -${NETWORK}
      -rpcuser=${RPCUSER}
      -rpcauth=${RPCAUTH}
      -rpcallowip=0.0.0.0/0
      -debug=${DEBUG}
      -zmqpubrawblock=tcp://*:28332
      -zmqpubrawtx=tcp://*:28332
      -zmqpubhashtx=tcp://*:28332
      -zmqpubhashblock=tcp://*:28332
      -txindex=${TXINDEX}
    expose:
     - "28332"
    ports:
     - "28332:28332"
     - "18332:18332"

  lnd:
    image: lnd
    container_name: lnd
    build:
      context: ${PWD}/lnd/
      dockerfile: ${PWD}/lnd/Dockerfile
    volumes:
      - ${PWD}/lnd_data:/root/.lnd
    environment:
      - RPCHOST=bitcoind
      - RPCUSER=${RPCUSER}
      - RPCPASS=${RPCPASSWORD}
      - NETWORK=${NETWORK}
      - CHAIN=${CHAIN}
      - DEBUG=${DEBUGLEVEL}
      - BITCOIN_NODE=${BITCOIN_NODE}
      - ZMQ_PATH=${ZMQ_PATH}
    entrypoint: ["./start-lnd.sh"]
    restart: always

    ports:
     - "10009:10009" # RPC
     - "8080:8080"   # REST
     - "9735:9735"   # p2p

  admin_website:
    image: admin_website
    container_name: admin_website
    build:
      context: ../services/admin_website
      dockerfile: ${PWD}/services/admin_website/Dockerfile
    environment:
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
      - BITCOIND_RPC_HOST=bitcoind
      - BITCOIND_RPC_USER=${RPCUSER}
      - BITCOIND_RPC_PASSWORD=${RPCPASSWORD}
      - NETWORK=${NETWORK}
      - LND_RPC_URI=lnd:10009
      - LND_PEER_URI=lnd:9735
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    volumes:
      - ${PWD}/data:/root/.bitcoin
      - ${PWD}/lnd_data:/root/.lnd
      - ${PWD}/../services/admin_website/app/app:/app/app
    ports:
     - "5000:80"

  logging_service:
    image: logging_service
    container_name: logging_service
    build:
      context: ../services/logging
      dockerfile: ${PWD}/services/logging/Dockerfile
    environment:
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
    volumes:
      - ${PWD}/data:/home/bitcoin/.bitcoin:ro
      - ${PWD}/lnd_data:/root/.lnd:ro
    ports:
     - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
